### ISSUE TITLE
Archbox update

### ISSUE THREAD

**Issue by BTechlab** [terlar/archbox#1]
sudo pacman -Syu fails complains about ttf-dejavu
sudo pacman -Syu --force ttf-dejavu also fails removes xorg-server
I'll just install arch the hardway and continue.

**Comment by terlar** [comment]
I haven't installed from scratch for a really long time, I will see if I can get that docker image wokring so I can try it out, or perhaps create a vagrant image. Any other issues? Can you remove those fonts? This has basically been adding most packages I use, so the thought is that others can modify as they need. I have tried to split up packages to make selection easier, but I guess it is mostly complicating things.

**Comment by BTechlab** [comment]
sudo pacman -Syu --ignore ttf-dejavu does not work either
will try rm /var/lib/pacman /db.lck before attempting to update.

**Comment by BTechlab** [comment]
sudo pacman -Rdd qt5-base
sudo pacman -Syu

**Comment by BTechlab** [comment]
no joy. complained about no virtualbox-guest, continued to update 240 packages then the screen went blank. I downloaded the .iso from Sorceforge who appear to be having issues. Selected a mirror site in NY, download ok. I'll try again next month.
